export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
export const FETCH_USERS_DATA = 'FETCH_USERS_DATA';
export const LOG_OUT = 'LOG_OUT';
export const REQUEST_FAILED = 'REQUEST_FAILED';
